permalink: /:year/:month/:title
title: alexand.ro
author:
  name: alexand.ro
  email: hello@alexand.ro
description: Pursuing the world of startups. Creating videos @Jurnalul Unui Olimpic. Ex-Software Engineer @Amazon.
url: 'https://alexand.ro'
twitter:
  username: 'alexand__ro'
  creator: 'alexand__ro'
  site: 'alexand__ro'
  card: 'summary_large_image'
facebook:
  app_id: 239202243681974
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
    values:
      layout: 'default'
social:
  name: alexand.ro
  links:
    - https://twitter.com/alexand__ro
    - https://youtube.com/channel/UCQQwkvM9vQ6AEl1CfnEtdrQ
